### ISSUE TITLE
Feature Req: Panoramic Floor

### ISSUE THREAD

**Issue by NeatWolf** [jverif/lc-shipwindow#1]
Hi!

I know it's a bit extreme but, since we're carving out the ship, why not go to full-extremes and make the hull even more fragile by carving most of the floor out?  :P 
I mean, in a way some touristic boats do, with a huge, scary transparent window you can walk on.

- I'm asking you as I really wanted some "tactical" windows in the past, and probably any other mod affecting the ship outer shell is not going to be compatible(I'm assuming you exported the model, subtracted a window and reimported it).

I also noticed there's very little to watch when landing, so maybe everyone could enjoy the scenery - not just those close to the window :)

Of course you can always opt-in to have the floor close when it lands/when it's in space.

_The Company has done some research and noticed a nice peak of adrenaline thanks to this feature - and adrenaline means productivity! :P 
Sure, the ship could depressurize or implode/explode easier but - think of all the precious scrap you can save building a ship with such window!_

as an extra - cool neon lights could be installed on the perimeter. Also, who needs lights when there's a free source below (maybe can be faked with one or two dim point lights on the floor)

As an inspiration:
![image](https://github.com/jverif/lc-shipwindow/assets/6001560/1608012a-0a6f-408e-97c7-ad112496a8b3)
![image](https://github.com/jverif/lc-shipwindow/assets/6001560/0eb13728-5245-49b0-840b-7eb1d59cd0a9)

Hopefully you like the idea and lot can be recycled from the code of the window :)

**Comment by jverif** [comment]
I definitely want to explore some more window locations, though I am somewhat hesitant to go all out since I'm sure a lot of people appreciate the simplicity of the current mod, and how it doesn't affect gameplay all too much beyond limited circumstances. I think a decent compromise could be to add these additional windows, but have them behind configuration settings so that you can configure for yourself which windows you like and don't like.

The only downside would be having to bundle a unique ship model for every possible window configuration, which now that I think about it, won't be that big of an issue at all considering it's only around 200 KB. The space skybox is nearly 40MB for reference.

I actually started working on this mod by trying a floor window first, but the position of the thrusters and some other junk under the ship made it look very out of place. The random stuff can simply be disabled, but the thrusters are a little more tricky since they sit more under the ship where you'd want to see out. I will just have to experiment with it.

I appreciate the suggestion :)

**Comment by NeatWolf** [comment]
40MB? Oh my!

Btw, the planets from afar are textured and all - wonder if adding a fake light outside the ship could make them stand more.
Apologies for the OT - feel free to close the "Bug" - this was the only link available to get in touch ^^

**Comment by jverif** [comment]
There is a mod that does just that actually. https://thunderstore.io/c/lethal-company/p/CatsArmy/SpaceSunShine/
It should be compatible with this mod. You'll just have to change the "HideSpaceProps" setting so the planets are visible.

**Comment by jverif** [comment]
Just to close the issue, will be adding some more windows in the next update, 1.3.0! Will be uploading later tonight.

**Comment by DaedalusGH** [comment]
So THIS is how we got the floor window? Very nice! I was really excited to see the update log and see "new windows added". I absolutely love the new windows, especially taking a step back to see all the windows at once to look at all the scenery. The extra windows do help a lot to take a look at what's happening outside without having to run all the way out, as well as just look nice.

**Comment by NeatWolf** [comment]
Coming back to say a sincere thank you for adding this feature, I'm so glad it turned out being so cool ^^
Thank you for all the time and effort you're putting into this! :3
