### ISSUE TITLE
Last version make it support vanilla...

### ISSUE THREAD

**Issue by xAstroBoy** [jverif/lc-shipwindow#4]
Title, this mod looks nice! why  this mod outside of 1.0.5 is not supporting vanilla?

**Comment by jverif** [comment]
After version 1.0.5, this mod registers at least two network prefabs, namely the WindowNetworkManager to hold RPCs and the Window Switch prefab, which is a ship object with an interact trigger, a vanilla network behavior. Which breaks network compatibility. I also plan for this mod to support windows as ship upgrades, which will be tracked with network objects as well.

I can add a setting that disables all of the network related features and skip registering the network prefabs, but it will break the window shutter and skybox for clients (not the host) because I patch server-side methods to control these objects. Additionally, the window switch is a placeable ship object and has a vanilla interact trigger which is also networked.

Is it possible to write a network manager using custom messages and rewrite all of the vanilla components and server-side event RPCs to go through it? Sure, but this is a simple mod made for fun, and doing all of that honestly sounds like a pain in the ass. You are welcome to have a go at it and submit a pull request if you do come up with something, but for now, it just isn't a priority.

Thanks
